{{- if .Values.istio.virtualService.enabled -}}
{{- $fullName := include "name" . -}}
{{- $hosts := required "A valid Values.istio.virtualService.hosts is required!" .Values.istio.virtualService.hosts -}}
{{- $gatewayNamespace := default "istio-system" .Values.istio.gateway.namespace -}}
{{- $gatewayName := default "istio-ingressgateway" .Values.istio.gateway.name -}}
{{- $gatewayFqdn := printf "%s/%s" $gatewayNamespace $gatewayName -}}
{{- $gatewayExternalV1 := lookup "networking.istio.io/v1" "Gateway" $gatewayNamespace $gatewayName -}}
{{- $gatewayExternalV1beta1 := lookup "networking.istio.io/v1beta1" "Gateway" $gatewayNamespace $gatewayName -}}
{{- $gatewayExists := or $gatewayExternalV1 $gatewayExternalV1beta1 -}}
################################################
# Standardized Templates - Istio VirtualService
################################################
apiVersion: {{ ternary "networking.istio.io/v1" "networking.istio.io/v1beta1" (.Capabilities.APIVersions.Has "networking.istio.io/v1") }}
kind: VirtualService
metadata:
  name: {{ if .Values.istio.virtualService.name }}{{ tpl .Values.istio.virtualService.name $ | quote }}{{ else }}{{ $fullName | quote }}{{ end }}
{{ include "labels" . | indent 2 }}
{{- with .Values.istio.virtualService.annotations }}
  annotations:
{{ tpl (toYaml .) $ | indent 4 }}
{{- end }}
spec:
  hosts:
{{- range $hosts }}
    - {{ tpl . $ | quote }}
{{- end }}
  gateways:
{{- if .Values.istio.virtualService.gateways }}
{{- range .Values.istio.virtualService.gateways }}
    - {{ tpl . $ | quote }}
{{- end }}
{{- else if $gatewayExists }}
    - {{ $gatewayFqdn | quote }}
{{- else if .Values.istio.gateway.createIfMissing }}
    - {{ $gatewayFqdn | quote }}
{{- else }}
    - mesh
{{- end }}
  http:
{{- if .Values.istio.virtualService.http }}
{{ tpl (toYaml .Values.istio.virtualService.http) $ | indent 4 }}
{{- else }}
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
{{- end }}
